apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  podMonitorSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  ruleSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  probeSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
