apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-controller-manager
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - path: /metrics
      portNumber: 10257
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      component: kube-controller-manager
      tier: control-plane
