apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  podMonitorSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  ruleSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  probeSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  resources:
    requests:
      memory: 2Gi
      cpu: 200m
