resources:
  - alertmanager
  - grafana
  - grafana-operator/v5.17.0
  - karma
  - kube-state-metrics/v2.15.0
  - prometheus
  - prometheus-adapter/v0.12.0
  - prometheus-operator/v0.81.0
patches:
  - path: overlays/adapter.yaml # link prometheus-adapter with our prometheus instance
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring-infra
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/instance: k8s-monitoring
      app.kubernetes.io/version: v0.0.1
