apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-api-server
spec:
  jobLabel: component
  endpoints:
    - port: https
      authorization: # use the Bearer token for authorization
        type: Bearer
        credentials:
          key: token
          name: prometheus-sa-token
      scheme: https # use https
      tlsConfig: # skip the verification of the certificate
        insecureSkipVerify: true
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - path: /metrics/slis
      authorization: # use the Bearer token for authorization
        type: Bearer
        credentials:
          key: token
          name: prometheus-sa-token
      scheme: https # use https
      tlsConfig: # skip the verification of the certificate
        insecureSkipVerify: true
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
