apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: k8s
spec:
  alertmanagerConfigSelector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring-infra
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
